language: cpp

compiler:
  - clang
    
before_install:
  - sudo add-apt-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main"
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake llvm-3.7 -y

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
