language: cpp

compiler:
  - clang
    
before_install:
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main"
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake clang-3.7 llvm-3.7 llvm-3.7-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
